language: objective-c
osx_image: xcode9.2
env:
  - DESTINATION="arch=x86_64"             PLATFORM=Mac
  - DESTINATION="OS=11.2,name=iPhone SE"  PLATFORM=iOS
cache:
  directories:
  - Carthage
install:
  - carthage bootstrap --cache-builds --no-use-binaries --platform $PLATFORM
script:
  - set -o pipefail
  - xcodebuild -scheme PMKCoreBluetooth -destination "$DESTINATION" clean build
  - xcodebuild -scheme PMKCoreBluetooth -destination "$DESTINATION" test
