language: objective-c
osx_image: xcode9.2
env:
  - DESTINATION="arch=x86_64"             PLATFORM=Mac
  - DESTINATION="OS=11.2,name=iPhone SE"  PLATFORM=iOS
cache:
  directories:
  - Carthage
before_install:
  - carthage bootstrap --cache-builds --no-use-binaries --platform $PLATFORM --verbose
install:
  - xcodebuild -scheme PMKCoreBluetooth -destination "$DESTINATION" build-for-testing
script:
  - xcodebuild -scheme PMKCoreBluetooth -destination "$DESTINATION" test
